version: "2.0"

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq-event-bus
        env_file: 
            - .env
        ports:
            - ${RABBITMQ_CLIENT_PORT}:${RABBITMQ_CLIENT_PORT}
            - ${RABBITMQ_SERVER_PORT}:${RABBITMQ_SERVER_PORT}   
    