version: "2.0"

services:
    rabbitmq:
        image: rabbitmq
        container_name: rabbitmq-event-bus
        env_file: 
            - .env
        ports:
            - ${RABBITMQ_WEB_UI_PORT}:${RABBITMQ_WEB_UI_PORT}
            - ${RABBITMQ_BROKER_PORT}:${RABBITMQ_BROKER_PORT}   
    