const COMMAND_BUS_IDENTIFIER = Symbol.for("ICommandBus");
const EVENT_BUS_IDENTIFIER = Symbol.for("IEvent");
const REPOSITYPY_IDENTIFIER = Symbol.for("Repository");

export {
	COMMAND_BUS_IDENTIFIER,
	EVENT_BUS_IDENTIFIER,
	REPOSITYPY_IDENTIFIER
};